export interface Locality {
  id: string;
  name: string;
  slug: string;
  type: "IT Park / Tech Hub" | "Coaching Hub" | "Residential / PG Hub" | "Commercial Center" | "University Hub" | "Downtown Hub";
  popularFor: string[];
  lat: number;
  lng: number;
}

export interface City {
  id: string;
  name: string;
  state: string;
  slug: string;
  tagline: string;
  localities: Locality[];
  isCustom?: boolean;
}

export const CITIES_AND_LOCALITIES: City[] = [
  {
    id: "pune",
    name: "Pune",
    state: "Maharashtra",
    slug: "pune",
    tagline: "Oxford of the East - IT Hub, Co-living, Great Weather & Culture",
    localities: [
      {
        id: "hinjawadi",
        name: "Hinjawadi",
        slug: "hinjawadi",
        type: "IT Park / Tech Hub",
        popularFor: ["Rajiv Gandhi Infotech Park", "Affordable PGs", "Tiffin Services", "Tech Professionals"],
        lat: 18.5913,
        lng: 73.7389,
      },
      {
        id: "viman-nagar",
        name: "Viman Nagar",
        slug: "viman-nagar",
        type: "Residential / PG Hub",
        popularFor: ["Symbiosis Campus", "Co-living Spaces", "Phoenix Mall", "Airport Corridor"],
        lat: 18.5679,
        lng: 73.9143,
      },
      {
        id: "wakad",
        name: "Wakad",
        slug: "wakad",
        type: "Residential / PG Hub",
        popularFor: ["New High-rises", "Zero Brokerage PGs", "Easy Highway Connect", "Freshers"],
        lat: 18.5987,
        lng: 73.7635,
      },
      {
        id: "baner",
        name: "Baner",
        slug: "baner",
        type: "Commercial Center",
        popularFor: ["Startups", "Premium PGs", "Boutique Cafes", "Co-working"],
        lat: 18.559,
        lng: 73.7868,
      },
      {
        id: "koregaon-park",
        name: "Koregaon Park",
        slug: "koregaon-park",
        type: "Downtown Hub",
        popularFor: ["Cosmopolitan Vibe", "Nightlife & Cafes", "Executive Co-living", "Green Lanes"],
        lat: 18.5362,
        lng: 73.894,
      },
      {
        id: "kothrud",
        name: "Kothrud",
        slug: "kothrud",
        type: "University Hub",
        popularFor: ["MIT WPU / Colleges", "Student Hostels", "Maharashtrian Mess", "Metro Access"],
        lat: 18.5074,
        lng: 73.8077,
      },
      {
        id: "kharadi",
        name: "Kharadi",
        slug: "kharadi",
        type: "IT Park / Tech Hub",
        popularFor: ["EON Free Zone", "World Trade Center", "Shared Flats", "Modern PGs"],
        lat: 18.5514,
        lng: 73.9348,
      },
    ],
  },
  {
    id: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    slug: "bengaluru",
    tagline: "Silicon Valley of India - IT, Startups & Vibrant City Life",
    localities: [
      {
        id: "koramangala",
        name: "Koramangala",
        slug: "koramangala",
        type: "IT Park / Tech Hub",
        popularFor: ["Startups", "PGs & Co-living", "Cafes", "Pubs"],
        lat: 12.9352,
        lng: 77.6245,
      },
      {
        id: "hsr-layout",
        name: "HSR Layout",
        slug: "hsr-layout",
        type: "IT Park / Tech Hub",
        popularFor: ["Co-living", "Food Mess", "Tech Hubs", "Parks"],
        lat: 12.9121,
        lng: 77.6446,
      },
      {
        id: "indiranagar",
        name: "Indiranagar",
        slug: "indiranagar",
        type: "Commercial Center",
        popularFor: ["Shopping", "Co-working", "Premium PGs", "Metro Connect"],
        lat: 12.9784,
        lng: 77.6408,
      },
      {
        id: "whitefield",
        name: "Whitefield",
        slug: "whitefield",
        type: "IT Park / Tech Hub",
        popularFor: ["IT Parks", "Affordable Flats", "Tiffin Delivery"],
        lat: 12.9698,
        lng: 77.7499,
      },
      {
        id: "electronic-city",
        name: "Electronic City",
        slug: "electronic-city",
        type: "IT Park / Tech Hub",
        popularFor: ["Techies", "Budget PGs", "Daily Tiffin"],
        lat: 12.8399,
        lng: 77.677,
      },
      {
        id: "bellandur",
        name: "Bellandur & Outer Ring Road",
        slug: "bellandur",
        type: "IT Park / Tech Hub",
        popularFor: ["EcoSpace Tech Park", "Shared Flats", "Cooks & Maids"],
        lat: 12.926,
        lng: 77.6762,
      },
    ],
  },
  {
    id: "delhi-ncr",
    name: "Delhi / NCR",
    state: "Delhi NCR",
    slug: "delhi-ncr",
    tagline: "Capital Hub - Corporate Hubs, UPSC & Metro Network",
    localities: [
      {
        id: "gurgaon-cyber-city",
        name: "Gurgaon Cyber City / Sec 44",
        slug: "gurgaon-cyber-city",
        type: "IT Park / Tech Hub",
        popularFor: ["Corporate MNCs", "Luxury PGs", "Shared Flats"],
        lat: 28.495,
        lng: 77.0895,
      },
      {
        id: "noida-sec-62",
        name: "Noida Sector 62 & 132",
        slug: "noida-sec-62",
        type: "IT Park / Tech Hub",
        popularFor: ["IT Hub", "Co-living", "Affordable Food"],
        lat: 28.6272,
        lng: 77.3725,
      },
      {
        id: "laxmi-nagar",
        name: "Laxmi Nagar & Nirman Vihar",
        slug: "laxmi-nagar",
        type: "Coaching Hub",
        popularFor: ["CA & UPSC Coaching", "Budget Rooms", "Mess Food"],
        lat: 28.6304,
        lng: 77.2777,
      },
      {
        id: "du-north-campus",
        name: "DU North Campus (Kamla Nagar)",
        slug: "du-north-campus",
        type: "University Hub",
        popularFor: ["Student PGs", "Book Markets", "Affordable Cafes"],
        lat: 28.689,
        lng: 77.209,
      },
      {
        id: "saket-malviya-nagar",
        name: "Saket & Malviya Nagar",
        slug: "saket-malviya-nagar",
        type: "Residential / PG Hub",
        popularFor: ["South Delhi Living", "Metro Line", "Food Hubs"],
        lat: 28.5244,
        lng: 77.2185,
      },
      {
        id: "old-rajinder-nagar",
        name: "Old Rajinder Nagar & Karol Bagh",
        slug: "old-rajinder-nagar",
        type: "Coaching Hub",
        popularFor: ["IAS Coaching Hub", "Libraries", "Tiffin Delivery"],
        lat: 28.6415,
        lng: 77.1825,
      },
    ],
  },
  {
    id: "pune",
    name: "Pune",
    state: "Maharashtra",
    slug: "pune",
    tagline: "Oxford of the East - IT Parks & Youth Culture",
    localities: [
      {
        id: "hinjawadi",
        name: "Hinjawadi Phase 1-3",
        slug: "hinjawadi",
        type: "IT Park / Tech Hub",
        popularFor: ["Rajiv Gandhi Tech Park", "IT PGs", "Mess Services"],
        lat: 18.5912,
        lng: 73.7389,
      },
      {
        id: "viman-nagar",
        name: "Viman Nagar",
        slug: "viman-nagar",
        type: "Residential / PG Hub",
        popularFor: ["Symbiosis", "Airport Road", "Co-living", "Cafes"],
        lat: 18.5679,
        lng: 73.9143,
      },
      {
        id: "kothrud",
        name: "Kothrud & Karve Nagar",
        slug: "kothrud",
        type: "Residential / PG Hub",
        popularFor: ["Quiet Neighborhoods", "Traditional Mess", "Study Libraries"],
        lat: 18.5074,
        lng: 73.8077,
      },
      {
        id: "wakad-baner",
        name: "Wakad & Baner",
        slug: "wakad-baner",
        type: "IT Park / Tech Hub",
        popularFor: ["Expressway Access", "Modern PGs", "Fitness & Gyms"],
        lat: 18.5987,
        lng: 73.7661,
      },
      {
        id: "kharadi",
        name: "Kharadi EON IT Park",
        slug: "kharadi",
        type: "IT Park / Tech Hub",
        popularFor: ["EON IT Hub", "World Trade Center", "High-rise Co-living"],
        lat: 18.5516,
        lng: 73.9352,
      },
    ],
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    slug: "mumbai",
    tagline: "City of Dreams - Finance, Media & Local Trains",
    localities: [
      {
        id: "andheri-west",
        name: "Andheri West & Lokhandwala",
        slug: "andheri-west",
        type: "Commercial Center",
        popularFor: ["Media & IT", "Shared PGs", "Local Train Line"],
        lat: 19.1363,
        lng: 72.8277,
      },
      {
        id: "powai",
        name: "Powai",
        slug: "powai",
        type: "IT Park / Tech Hub",
        popularFor: ["IIT Bombay", "Hiranandani", "Startup Hub"],
        lat: 19.1176,
        lng: 72.906,
      },
      {
        id: "bkc-bandra",
        name: "BKC & Bandra East",
        slug: "bkc-bandra",
        type: "Commercial Center",
        popularFor: ["Financial District", "Professional PGs"],
        lat: 19.0657,
        lng: 72.8687,
      },
      {
        id: "navi-mumbai-vashi",
        name: "Navi Mumbai (Vashi & Airoli)",
        slug: "navi-mumbai-vashi",
        type: "IT Park / Tech Hub",
        popularFor: ["Mindspace IT Park", "Affordable Living", "Clean Hub"],
        lat: 19.0771,
        lng: 72.9986,
      },
    ],
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    slug: "hyderabad",
    tagline: "Cyberabad - IT Corridor & Biryani Capital",
    localities: [
      {
        id: "hitec-city",
        name: "HITEC City & Madhapur",
        slug: "hitec-city",
        type: "IT Park / Tech Hub",
        popularFor: ["Tech Parks", "Hostels & PGs", "Night Dining"],
        lat: 17.4435,
        lng: 78.3772,
      },
      {
        id: "gachibowli",
        name: "Gachibowli & Financial District",
        slug: "gachibowli",
        type: "IT Park / Tech Hub",
        popularFor: ["MNCs", "Sports Hub", "High-rise Co-living"],
        lat: 17.4401,
        lng: 78.3489,
      },
      {
        id: "ameerpet",
        name: "Ameerpet",
        slug: "ameerpet",
        type: "Coaching Hub",
        popularFor: ["Software Training", "Budget PGs", "Second-hand Books"],
        lat: 17.4375,
        lng: 78.4482,
      },
      {
        id: "kondapur",
        name: "Kondapur & Botanical Garden",
        slug: "kondapur",
        type: "Residential / PG Hub",
        popularFor: ["Peaceful PGs", "Family Flats", "Parks"],
        lat: 17.4649,
        lng: 78.3644,
      },
    ],
  },
  {
    id: "kota",
    name: "Kota",
    state: "Rajasthan",
    slug: "kota",
    tagline: "Coaching Capital of India - JEE, NEET & Student Life",
    localities: [
      {
        id: "rajeev-gandhi-nagar",
        name: "Rajeev Gandhi Nagar",
        slug: "rajeev-gandhi-nagar",
        type: "Coaching Hub",
        popularFor: ["Allen SAMANVAY", "Hostels", "Mess", "Stationary"],
        lat: 25.1382,
        lng: 75.8459,
      },
      {
        id: "landmark-city",
        name: "Landmark City (Kunhari)",
        slug: "landmark-city",
        type: "Coaching Hub",
        popularFor: ["Allen SANGYAN", "Girls & Boys Hostels", "Laundry"],
        lat: 25.2052,
        lng: 75.8475,
      },
      {
        id: "talwandi",
        name: "Talwandi & Jawahar Nagar",
        slug: "talwandi",
        type: "Coaching Hub",
        popularFor: ["Resonance", "Career Point", "PG Rooms"],
        lat: 25.1506,
        lng: 75.843,
      },
    ],
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    slug: "jaipur",
    tagline: "Pink City - Tourism, Startups & Educational Hub",
    localities: [
      {
        id: "malviya-nagar-jaipur",
        name: "Malviya Nagar & Gaurav Tower",
        slug: "malviya-nagar-jaipur",
        type: "Commercial Center",
        popularFor: ["MNIT Jaipur", "GT Mall", "Hostels", "Food Cafes"],
        lat: 26.8549,
        lng: 75.8243,
      },
      {
        id: "vaishali-nagar",
        name: "Vaishali Nagar",
        slug: "vaishali-nagar",
        type: "Residential / PG Hub",
        popularFor: ["Clean Neighborhoods", "Family Flats", "Gyms"],
        lat: 26.9056,
        lng: 75.7423,
      },
      {
        id: "mansarovar",
        name: "Mansarovar",
        slug: "mansarovar",
        type: "University Hub",
        popularFor: ["Metro Line", "Affordable PGs", "Mess Services"],
        lat: 26.853,
        lng: 75.7679,
      },
    ],
  },
  {
    id: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    slug: "indore",
    tagline: "Cleanest City of India - Food Paradise & Emerging IT Hub",
    localities: [
      {
        id: "vijay-nagar",
        name: "Vijay Nagar & Scheme 54",
        slug: "vijay-nagar",
        type: "IT Park / Tech Hub",
        popularFor: ["IT Crystal Park", "Brilliant Convention", "Co-living"],
        lat: 22.7533,
        lng: 75.8937,
      },
      {
        id: "bhawarkua",
        name: "Bhawarkua & Tower Chouraha",
        slug: "bhawarkua",
        type: "Coaching Hub",
        popularFor: ["MPPSC & UPSC Coaching", "Budget Hostels", "Sarafa Food"],
        lat: 22.6926,
        lng: 75.8677,
      },
      {
        id: "palasia",
        name: "Old & New Palasia",
        slug: "palasia",
        type: "Commercial Center",
        popularFor: ["Chhappan Dukan", "Cafes", "Central Connectivity"],
        lat: 22.7244,
        lng: 75.8839,
      },
    ],
  },
  {
    id: "chandigarh",
    name: "Chandigarh / Tricity",
    state: "Punjab / Haryana",
    slug: "chandigarh",
    tagline: "The City Beautiful - High Standard of Living & Tech Parks",
    localities: [
      {
        id: "chandigarh-sec-35",
        name: "Sector 34 & 35",
        slug: "chandigarh-sec-35",
        type: "Coaching Hub",
        popularFor: ["Coaching Institutes", "Student PGs", "Food Streets"],
        lat: 30.7242,
        lng: 76.7645,
      },
      {
        id: "mohali-phase-8",
        name: "Mohali Phase 7 & 8 (IT Hub)",
        slug: "mohali-phase-8",
        type: "IT Park / Tech Hub",
        popularFor: ["QuarkCity", "IT Startups", "Independent Flats"],
        lat: 30.7046,
        lng: 76.7179,
      },
    ],
  },
  {
    id: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    slug: "chennai",
    tagline: "Gateway to South India - Automobile & OMR IT Corridor",
    localities: [
      {
        id: "omr-thoraipakkam",
        name: "OMR (Thoraipakkam & Sholinganallur)",
        slug: "omr-thoraipakkam",
        type: "IT Park / Tech Hub",
        popularFor: ["IT Expressway", "Tech Parks", "Gated Communities"],
        lat: 12.9348,
        lng: 80.2312,
      },
      {
        id: "velachery",
        name: "Velachery & Guindy",
        slug: "velachery",
        type: "Commercial Center",
        popularFor: ["Phoenix Marketcity", "Metro Line", "Affordable PGs"],
        lat: 12.9759,
        lng: 80.2212,
      },
    ],
  },
  {
    id: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    slug: "ahmedabad",
    tagline: "Manchester of India - Business, Heritage & GIFT City Corridor",
    localities: [
      {
        id: "sg-highway",
        name: "SG Highway & Prahlad Nagar",
        slug: "sg-highway",
        type: "IT Park / Tech Hub",
        popularFor: ["Corporate Parks", "GIFT City Commute", "Modern PGs"],
        lat: 23.0131,
        lng: 72.5058,
      },
      {
        id: "navrangpura",
        name: "Navrangpura & CG Road",
        slug: "navrangpura",
        type: "University Hub",
        popularFor: ["Gujarat University", "IIM Ahmedabad area", "Bookshops"],
        lat: 23.0373,
        lng: 72.5526,
      },
    ],
  },
  {
    id: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    slug: "lucknow",
    tagline: "City of Nawabs - Culture, Modern Gomti Nagar & Govt Hub",
    localities: [
      {
        id: "gomti-nagar",
        name: "Gomti Nagar & Gomti Nagar Extension",
        slug: "gomti-nagar",
        type: "IT Park / Tech Hub",
        popularFor: ["HCL IT City", "Riverside Mall", "Modern Apartments"],
        lat: 26.8529,
        lng: 80.9992,
      },
      {
        id: "hazratganj",
        name: "Hazratganj & Aliganj",
        slug: "hazratganj",
        type: "Commercial Center",
        popularFor: ["Central Hub", "Coaching Hubs", "Metro Connectivity"],
        lat: 26.8467,
        lng: 80.9462,
      },
    ],
  },
  {
    id: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    slug: "kolkata",
    tagline: "City of Joy - Salt Lake Sector V IT Hub & Rich Heritage",
    localities: [
      {
        id: "salt-lake-sec-v",
        name: "Salt Lake Sector V & New Town",
        slug: "salt-lake-sec-v",
        type: "IT Park / Tech Hub",
        popularFor: ["IT Sector V", "Eco Park", "Co-living Highrises"],
        lat: 22.5804,
        lng: 88.4378,
      },
      {
        id: "south-kolkata",
        name: "Ballygunge & Jadavpur",
        slug: "south-kolkata",
        type: "University Hub",
        popularFor: ["Jadavpur University", "South City Mall", "Affordable Mess"],
        lat: 22.4996,
        lng: 88.3716,
      },
    ],
  },
];

// Helper to support ANY city dynamically in real-time
export function getOrCreateCity(cityName: string): City {
  const normalized = cityName.trim().toLowerCase();
  const existing = CITIES_AND_LOCALITIES.find(
    (c) => c.name.toLowerCase() === normalized || c.slug === normalized || c.id === normalized
  );

  if (existing) return existing;

  // Dynamically generate city object
  const slug = normalized.replace(/[^a-z0-9]+/g, "-");
  const formattedName = cityName.trim().charAt(0).toUpperCase() + cityName.trim().slice(1);

  return {
    id: slug,
    name: formattedName,
    state: "India",
    slug: slug,
    tagline: `Discover verified PGs, food, jobs & essentials in ${formattedName}`,
    isCustom: true,
    localities: [
      {
        id: `${slug}-central`,
        name: `${formattedName} Central / Downtown`,
        slug: `${slug}-central`,
        type: "Commercial Center",
        popularFor: ["Main Market", "Transit Hub", "Daily Services"],
        lat: 20.5937,
        lng: 78.9629,
      },
      {
        id: `${slug}-tech-hub`,
        name: `${formattedName} Tech & Education Zone`,
        slug: `${slug}-tech-hub`,
        type: "IT Park / Tech Hub",
        popularFor: ["Offices", "PGs & Hostels", "Food Mess"],
        lat: 20.5937,
        lng: 78.9629,
      },
      {
        id: `${slug}-residential`,
        name: `${formattedName} Residential & Suburbs`,
        slug: `${slug}-residential`,
        type: "Residential / PG Hub",
        popularFor: ["Shared Flats", "Quiet Neighborhood", "Maid Services"],
        lat: 20.5937,
        lng: 78.9629,
      },
    ],
  };
}
